ARG HADOOP_IMAGE

FROM $HADOOP_IMAGE

ARG HADOOP_VERSION
ARG SSM_APP_VERSION
ENV HADOOP_VERSION=$HADOOP_VERSION
ENV HADOOP_HOME=/opt/hadoop-$HADOOP_VERSION
ENV HADOOP_CONF_DIR=/etc/hadoop
ENV MULTIHOMED_NETWORK=1
ENV USER=root
ENV PATH $HADOOP_HOME/bin/:$PATH
ENV HDFS_PARENT_DATA_DIR=/hadoop/dfs
ENV SSM_HOME=/opt/ssm
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH $JAVA_HOME/bin:$PATH

RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-11-jre-headless \
    && ln -sf $JAVA_HOME/bin/java /usr/local/bin/java \
    && rm -rf /var/lib/apt/lists/*

# Copy ssm client jar to $HADOOP_HOME/share/hadoop/common/lib
COPY target/smart-data-${SSM_APP_VERSION}/clients/smart-hadoop-client-shaded-${SSM_APP_VERSION}.jar $HADOOP_HOME/share/hadoop/common/lib/
COPY target/smart-data-${SSM_APP_VERSION}/lib/*.jar $SSM_HOME/lib/
COPY target/smart-data-${SSM_APP_VERSION}/bin/* $SSM_HOME/bin/

RUN chmod a+x $SSM_HOME/bin/install.sh
RUN chmod a+x $SSM_HOME/bin/start-ssm.sh
RUN chmod a+x $SSM_HOME/bin/start-agent.sh

# docker-relative-dir is assembly build context relative directory, more info below
# https://maven.fabric8.io/#build-configuration  'Adding assemblies in Dockerfile mode'
ADD docker-relative-dir/docker/multihost/common.sh /common.sh
ADD docker-relative-dir/docker/multihost/hadoop-base-entrypoint.sh /hadoop-base-entrypoint.sh
RUN chmod a+x /common.sh
RUN chmod a+x /hadoop-base-entrypoint.sh

ENTRYPOINT ["/hadoop-base-entrypoint.sh"]
