ARG HADOOP_IMAGE

FROM $HADOOP_IMAGE

ARG HADOOP_VERSION
ARG SSM_APP_VERSION
ENV HADOOP_VERSION=$HADOOP_VERSION
ENV HADOOP_HOME=/opt/hadoop-$HADOOP_VERSION
ENV HADOOP_CONF_DIR=/etc/hadoop
ENV MULTIHOMED_NETWORK=1
ENV USER=root
ENV PATH $HADOOP_HOME/bin/:$PATH
ENV HDFS_PARENT_DATA_DIR=/hadoop/dfs
ENV SSM_HOME=/opt/ssm

# Copy ssm client jar to $HADOOP_HOME/share/hadoop/common/lib
COPY target/smart-data-${SSM_APP_VERSION}/clients/smart-hadoop-client-shaded-${SSM_APP_VERSION}.jar $HADOOP_HOME/share/hadoop/common/lib/
COPY target/smart-data-${SSM_APP_VERSION}/lib/*.jar $SSM_HOME/lib/
COPY target/smart-data-${SSM_APP_VERSION}/bin/* $SSM_HOME/bin/

RUN chmod a+x $SSM_HOME/bin/install.sh
RUN chmod a+x $SSM_HOME/bin/start-ssm.sh
RUN chmod a+x $SSM_HOME/bin/start-agent.sh

ADD src/docker/multihost/common.sh /common.sh
ADD src/docker/multihost/hadoop-base-entrypoint.sh /hadoop-base-entrypoint.sh
RUN chmod a+x /common.sh
RUN chmod a+x /hadoop-base-entrypoint.sh

ENTRYPOINT ["/hadoop-base-entrypoint.sh"]