- name: Ensures /usr/lib/ssm/lib/ dir exists
  become: yes
  file:
    path: "/usr/lib/ssm/lib/"
    state: directory
    recurse: yes

- name: Find old SSM jars to delete
  find:
    paths: /usr/lib/ssm/lib
    patterns: "*.jar"
    recurse: yes
  register: old_ssm_jars_to_delete

- name: Remove old SSM jars
  become: yes
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ old_ssm_jars_to_delete.files }}"

- name: Copy new SSM jars
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/lib/ssm/lib/"
  with_fileglob:
    - "../smart-dist/target/smart-data-1.6.0-SNAPSHOT/lib/*.jar"
