- name: Gather facts
  hosts: all

- name: Update SSM Agents
  hosts: ssm_agents
  gather_facts: no
  tasks:
#    - name: Stop SSM agent systemd service
#      ansible.builtin.systemd_service:
#        name: smart-storage-manager-agent.service
#        state: stopped

    - include_tasks: copy_ssm_jars_tasks.yaml

    - name: Start SSM agent systemd service
      ansible.builtin.systemd_service:
        name: smart-storage-manager-agent.service
        state: started

- name: Update SSM Servers
  hosts: ssm_servers
  gather_facts: no
  tasks:
    - name: Stop SSM server systemd service
      ansible.builtin.systemd_service:
        name: smart-storage-manager-server.service
        state: stopped

    - include_tasks: copy_ssm_jars_tasks.yaml

    - name: Create PostgreSQL driver symbolic link
      become: yes
      ansible.builtin.copy:
        src: /usr/share/java/jdbc-postgresql.jar
        dest: /usr/lib/ssm/lib/postgresql-jdbc.jar
        state: link

    - name: Start SSM server systemd service
      ansible.builtin.systemd_service:
        name: smart-storage-manager-server.service
        state: started
