- name: Gather facts
  hosts: all

- name: Update SSM Agents
  hosts: ssm_agents
  gather_facts: no
  tasks:
    - include_tasks: restart_service_tasks.yaml
      vars:
        ssm_service_name: smart-storage-manager-agent
        ssm_version: 1.6.0-SNAPSHOT

- name: Update SSM Servers
  hosts: ssm_servers
  gather_facts: no
  tasks:
    - include_tasks: restart_service_tasks.yaml
      vars:
        ssm_service_name: smart-storage-manager-server
        ssm_version: 1.6.0-SNAPSHOT

    # restore postgresql driver jar symlink created by adcm
    # to be able to correctly run adcm actions from web ui
    - name: Create PostgreSQL driver symbolic link
      become: yes
      ansible.builtin.file:
        src: /usr/share/java/jdbc-postgresql.jar
        dest: /usr/lib/ssm/lib/postgresql-jdbc.jar
        state: link
