<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.smartdata</groupId>
        <artifactId>smartdata-project</artifactId>
        <version>2.2.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>smart-dist</artifactId>
    <version>2.2.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <docker-maven-plugin.version>0.46.0</docker-maven-plugin.version>
        <!--        Image properties:-->
        <!--        ssm-hadoop-base image-->
        <hadoop.ssm.image.name>hub.adsw.io/ssm/ssm-hadoop-base</hadoop.ssm.image.name>
        <hadoop.ssm.image.tag>3.3.6</hadoop.ssm.image.tag>
        <hadoop.ssm.image.file>../supports/tools/docker/multihost/Dockerfile-hadoop-base</hadoop.ssm.image.file>
        <hadoop.base.image.name>hub.adsw.io/java/hadoop-openjdk8</hadoop.base.image.name>
        <hadoop.base.image.tag>3.3.6</hadoop.base.image.tag>
        <!--        ssm-server image-->
        <ssm.server.image.name>hub.adsw.io/ssm/ssm-server</ssm.server.image.name>
        <ssm.server.image.tag>${version}</ssm.server.image.tag>
        <ssm.server.image.file>../supports/tools/docker/multihost/ssm/Dockerfile-ssm-server</ssm.server.image.file>
    </properties>


    <dependencies>
        <dependency>
            <groupId>org.smartdata</groupId>
            <artifactId>smart-common</artifactId>
            <version>2.2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.smartdata</groupId>
            <artifactId>smart-client</artifactId>
            <version>2.2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.smartdata</groupId>
            <artifactId>smart-inputstream</artifactId>
            <version>2.2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.smartdata</groupId>
            <artifactId>smart-action</artifactId>
            <version>2.2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.smartdata</groupId>
            <artifactId>smart-engine</artifactId>
            <version>2.2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.smartdata</groupId>
            <artifactId>smart-server</artifactId>
            <version>2.2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.smartdata</groupId>
            <artifactId>${smart.hadoop.artifact}</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.smartdata</groupId>
            <artifactId>${smart.hadoop.client.artifact}</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.smartdata</groupId>
            <artifactId>smart-agent</artifactId>
            <version>2.2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.smartdata</groupId>
            <artifactId>smart-integration</artifactId>
            <version>2.2.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>dist</id>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-assembly-plugin</artifactId>
                        <version>3.0.0</version>
                        <executions>
                            <execution>
                                <id>distro-assembly</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>single</goal>
                                </goals>
                                <configuration>
                                    <finalName>smart-data-${project.version}</finalName>
                                    <appendAssemblyId>false</appendAssemblyId>
                                    <descriptors>
                                        <descriptor>src/assemblies/bin.xml</descriptor>
                                        <descriptor>src/assemblies/bin_tar.xml</descriptor>
                                    </descriptors>
                                    <attach>false</attach>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>with-docker</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.fabric8</groupId>
                        <artifactId>docker-maven-plugin</artifactId>
                        <version>${docker-maven-plugin.version}</version>
                        <configuration>
                            <verbose>true</verbose>
                            <images>
                                <image>
                                    <name>${hadoop.ssm.image.name}:${hadoop.ssm.image.tag}</name>
                                    <build>
                                        <assembly>
                                            <inline>
                                                <fileSets>
                                                    <fileSet>
                                                        <directory>../supports/tools/docker</directory>
                                                        <outputDirectory>/docker</outputDirectory>
                                                        <includes>
                                                            <include>**/*</include>
                                                        </includes>
                                                        <useDefaultExcludes>false</useDefaultExcludes>
                                                    </fileSet>
                                                </fileSets>
                                            </inline>
                                        </assembly>
                                        <contextDir>${basedir}</contextDir>
                                        <dockerFile>${hadoop.ssm.image.file}</dockerFile>
                                        <args>
                                            <HADOOP_IMAGE>${hadoop.base.image.name}:${hadoop.base.image.tag}
                                            </HADOOP_IMAGE>
                                            <SSM_APP_VERSION>${version}</SSM_APP_VERSION>
                                        </args>
                                    </build>
                                </image>
                                <image>
                                    <name>${ssm.server.image.name}:${ssm.server.image.tag}</name>
                                    <build>
                                        <assembly>
                                            <inline>
                                                <fileSets>
                                                    <fileSet>
                                                        <directory>../supports/tools/docker</directory>
                                                        <outputDirectory>/docker</outputDirectory>
                                                        <includes>
                                                            <include>**/*</include>
                                                        </includes>
                                                        <useDefaultExcludes>false</useDefaultExcludes>
                                                    </fileSet>
                                                </fileSets>
                                            </inline>
                                        </assembly>
                                        <contextDir>${basedir}</contextDir>
                                        <dockerFile>${ssm.server.image.file}</dockerFile>
                                        <args>
                                            <SSM_APP_VERSION>${version}</SSM_APP_VERSION>
                                        </args>
                                    </build>
                                </image>
                            </images>
                        </configuration>
                        <executions>
                            <execution>
                                <id>build SSM docker images</id>
                                <phase>install</phase>
                                <goals>
                                    <goal>build</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>