general:
  # env-type: docker|remote
  env-type: ${ENV_TYPE:docker}
  browser-manager: ${BROWSER_MANAGER:moon} # local|selenoid|moon
  ci: ${CI:false}
  protocol: ${PROTOCOL:http}
  bundle-run: ${BUNDLE_RUN:false}
  selenoid-compose-file-name: ${SELENOID_COMPOSE_FILE_NAME:target/common-resources/selenoid/docker-compose.yaml}
  topology: ${TOPOLOGY:default}
  base-url: ${PROTOCOL:http}://${SSM_HOST:localhost}:${SSM_PORT:8081}

topologies:
  default: target/test-classes/env/multihost/docker-compose.yaml
  hms: target/test-classes/env/hms-cluster/docker-compose.yaml


docker-compose-service:
  # container-management-strategy: generic|compose
  container-management-strategy: ${CONTAINER_MANAGEMENT_STRATEGY:generic}

grids:
  list:
    - type: selenoid
      proxyHost: ${SELENOID_PROXY_HOST:172.17.0.1}
      remoteHost: ${SELENOID_REMOTE_HOST:http://localhost:4444}
      browserName: ${BROWSER_NAME:chrome}
      browserVersion: ${BROWSER_VERSION:stable}
      screenshot-successful-steps: true

    - type: moon
      proxyHost: ${MOON_PROXY_HOST:10.94.12.187}
      remoteHost: ${MOON_REMOTE_HOST:https://moon.dev.adsw.io}
      browserName: ${BROWSER_NAME:chrome}
      browserVersion: ${BROWSER_VERSION:150.0.7871.186}
      screenshot-successful-steps: true

    - type: local
      browserName: ${BROWSER_NAME:chrome}
      screenshot-successful-steps: false

logs:
  docker-logs-directory: target/allure-results
  docker-logs-archive-name: logs.zip

ssm-web:
  credentials:
    - role: OWNER
      login: john
      password: 1234
    - role: KERBEROS
      login: krb_user1@DEMO
      password: krb_pass1

remote:
  connectionTimeoutSec: 30
  services:
    - component: ssm-server
      ssh-config:
        host: ${SSM_HOST:localhost}
        port: 22
        authType: PUBLIC_KEY
        sshFilePath: "test.key"
        username: test
        password: test
      commands:
        startCommand:
        stopCommand:
    - component: ssm-metastore-db
      ssh-config:
        host: ${SSM_HOST:localhost}
        port: 22
        authType: PUBLIC_KEY
        sshFilePath: "test.key"
        username: test
        password: test
      commands:
        startCommand:
        stopCommand:
    - component: hadoop-namenode
      ssh-config:
        host: ${HADOOP_NAMENODE_HOST:localhost}
        port: 22
        authType: PUBLIC_KEY
        sshFilePath: "test.key"
        username: test
        password: test
      commands:
        startCommand:
        stopCommand:
    - component: hadoop-datanode
      ssh-config:
        host: ${HADOOP_DATANODE_HOST:localhost}
        port: 22
        authType: PUBLIC_KEY
        sshFilePath: "test.key"
        username: test
        password: test
      commands:
        startCommand:
        stopCommand:

ssm-metastore-db:
  datasource:
    jdbc-url: jdbc:postgresql://${METASTORE_DB_HOST:localhost}:5432/metastore
    username: ssm
    password: ssm
    schema: public
    driver-class-name: org.postgresql.Driver

ssm-hive-db:
  datasource:
    jdbc-url: jdbc:postgresql://${METASTORE_DB_HOST:localhost}:5432/hive
    username: ssm
    password: ssm
    schema: public
    driver-class-name: org.postgresql.Driver

ssm-hive2-db:
  datasource:
    jdbc-url: jdbc:postgresql://${METASTORE_DB_HOST:localhost}:5432/hive2
    username: ssm
    password: ssm
    schema: public
    driver-class-name: org.postgresql.Driver

hive-server2-db:
  datasource:
    jdbc-url: jdbc:hive2://${HIVE_SERVER_HOST:localhost}:10000/default
    driver-class-name: org.apache.hive.jdbc.HiveDriver

target-hive-server2-db:
  datasource:
    jdbc-url: jdbc:hive2://${TARGET_HIVE_SERVER_HOST:localhost}:10004/default
    driver-class-name: org.apache.hive.jdbc.HiveDriver

hms-profile-enabled: ${HMS_PROFILE_ENABLED:false}

# Reverse tunnel configuration to make Moon able to access test env on local machine
ssh-tunnel:
  host: ${SSH_TUNNEL_HOST:10.94.12.187}
  # Use run configuration or system env vars to override secrets
  username: ${SSH_TUNNEL_USERNAME:ssh_user}
  key-path: ${SSH_TUNNEL_KEY_PATH:/home/username/.ssh/key}
  key-passphrase: ${SSH_TUNNEL_KEY_PASSPHRASE:password}
  ssh-port: 22
  forward-host: 0.0.0.0
  forward-port-min: 9000
  port-range: 1000
  localhost: localhost
